### PR TITLE
Update gcloud-datastore to 3.0.1 and fix NPM audit

### PR DESCRIPTION
**Pull request by tonymet**
* update all deps to latest
* use eslintrc instead of jscs (deprecated)
* update to latest google-cloud-storage

## Test Results
```
➜  botkit-storage-datastore git:(feature/npm-audit-2019-01-24) npm test

> botkit-storage-datastore@1.0.0 pretest /Users/tonym/sotion/botkit-storage-datastore
> eslint ./


> botkit-storage-datastore@1.0.0 test /Users/tonym/sotion/botkit-storage-datastore
> istanbul cover --report lcov --dir coverage/ _mocha ./tests/index.js  -- --colors



  Datastore
    init
      ✓ should require a config
      ✓ should require projectId
      ✓ should initialize datastore with projectId
    key
      ✓ should use custom kind
    get
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    get from namespace
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    save
      ✓ should call datastore save
    save into namespace
      ✓ should call datastore save
    all
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    all from namespace
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    delete
      ✓ should call datastore delete
    save into namespace
      ✓ should call datastore save
    key
      ✓ should use custom kind
    get
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    get from namespace
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    save
      ✓ should call datastore save
    save into namespace
      ✓ should call datastore save
    all
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    all from namespace
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    delete
      ✓ should call datastore delete
    save into namespace
      ✓ should call datastore save
    key
      ✓ should use custom kind
    get
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    get from namespace
      ✓ should get entity
      ✓ should handle non existent entity
      ✓ should call callback on error
    save
      ✓ should call datastore save
    save into namespace
      ✓ should call datastore save
    all
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    all from namespace
      ✓ should get records
      ✓ should handle no records
      ✓ should call callback on error
    delete
      ✓ should call datastore delete
    save into namespace
      ✓ should call datastore save


  54 passing (430ms)

=============================================================================
Writing coverage object [/Users/tonym/sotion/botkit-storage-datastore/coverage/coverage.json]
Writing coverage reports at [/Users/tonym/sotion/botkit-storage-datastore/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 42/42 )
Branches     : 100% ( 26/26 )
Functions    : 100% ( 12/12 )
Lines        : 100% ( 42/42 )
================================================================================
➜  botkit-storage-datastore git:(feature/npm-audit-2019-01-24)
```

### CODE REVIEW

**Comment by tonymet** [comment]
@fabito just doing some sheepherding

**Comment by fabito** [comment]
Thanks @tonymet  !
Can you check why the build is failing ? My guess is that we need to upgrade `,travis.yaml` to a newer nodejs version.

**Comment by tonymet** [comment]
@fabito I updated the node environment versions to test node 8-lts, 10-lts & 11(current).  It is now building.

**Review by fabito — APPROVED** [review]
LGTM

**Pull request merged**
